name       : falkon
version    : 3.0.0
release    : 10
source     :
    - https://download.kde.org/stable/falkon/3.0/src/falkon-3.0.0.tar.xz : 4e42a091e6ae434d7c3146adb876a8a5dc29d9354560087a905a0bd7fb58d7a6
license    : GPL-3.0
component  : network.web.browser
summary    : Falkon (formerly QupZilla) is a new and very fast QtWebEngine browser
description: |
    Falkon (formerly QupZilla) is a new and very fast QtWebEngine browser
replaces   :
    - qupzilla
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-atom)
    - extra-cmake-modules
setup      : |
    %cmake
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
    install -Dm00644 linux/completion/_falkon $installdir/usr/share/zsh/site-functions/_falkon
