name       : qupzilla
version    : 2.1.2
release    : 3
source     :
    - https://github.com/QupZilla/qupzilla/releases/download/v2.1.2/QupZilla-2.1.2.tar.xz : d8f860d8c41bbf2bf78889aef3ffed118a34b2754f7e114ad44eb2c6103ee58a
license    : GPL-3.0
component  : network.web.browser
summary    : QupZilla is a new and very fast QtWebEngine browser
description: |
    QupZilla is a new and very fast QtWebEngine browser
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-atom)
setup      : |
    export USE_LIBPATH=%libdir%
    export DISABLE_UPDATES_CHECK="true"

    %patch -p1 < $pkgfiles/QupZilla-2.0.1-openssl11.patch
    %qmake
build      : |
    export USE_LIBPATH=%libdir%
    export DISABLE_UPDATES_CHECK="true"

    %make
install    : |
    export USE_LIBPATH=%libdir%
    export DISABLE_UPDATES_CHECK="true"

    %make_install INSTALL_ROOT=$installdir

    install -Dm644 linux/completion/_qupzilla $installdir/usr/share/zsh/site-functions/_qupzilla

