name       : falkon
version    : 3.0.1
release    : 13
source     :
    - https://cdn.download.kde.org/stable/falkon/3.0.1/falkon-3.0.1.tar.xz : 7b6ed54986543dd5462602943fb824df12f15d2061996310c4c4b891433f1a83
license    : GPL-3.0-or-later
component  : network.web.browser
summary    : Falkon (formerly QupZilla) is a new and very fast QtWebEngine browser
description: |
    Falkon (formerly QupZilla) is a new and very fast QtWebEngine browser
replaces   :
    - qupzilla
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-atom)
    - extra-cmake-modules
    - ki18n-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -Dm00644 linux/completion/_falkon $installdir/usr/share/zsh/site-functions/_falkon
