name       : qupzilla
version    : 2.2.2
release    : 7
source     :
    - https://github.com/QupZilla/qupzilla/releases/download/v2.2.2/QupZilla-2.2.2.tar.xz : 090e60aba46ef2239df5af2cf50fcf10124937b573e90c72802c259145e5ba01
license    : GPL-3.0
component  : network.web.browser
summary    : QupZilla is a new and very fast QtWebEngine browser
description: |
    QupZilla is a new and very fast QtWebEngine browser
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-atom)
setup      : |
    export USE_LIBPATH=%libdir%
    export DISABLE_UPDATES_CHECK="true"
    %qmake
build      : |
    export USE_LIBPATH=%libdir%
    export DISABLE_UPDATES_CHECK="true"
    %make
install    : |
    export USE_LIBPATH=%libdir%
    export DISABLE_UPDATES_CHECK="true"
    %make_install INSTALL_ROOT=$installdir
    install -Dm00644 linux/completion/_qupzilla $installdir/usr/share/zsh/site-functions/_qupzilla

