name       : qupzilla
version    : 2.0.2
release    : 1
source     :
    - https://github.com/QupZilla/qupzilla/releases/download/v2.0.2/QupZilla-2.0.2.tar.xz : da4f9b3441386cfcc3000b950c40daa8818380d69b5054f156a345fdbac3855a
license    : GPL-3.0
component  : network.web.browser
summary    : QupZilla is a new and very fast QtWebEngine browser
description: |
    QupZilla is a new and very fast QtWebEngine browser
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-atom)
setup      : |
    %qmake
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
