name       : falkon
version    : 3.1.0
release    : 18
source     :
    - https://origin.download.kde.org/stable/falkon/3.1/falkon-3.1.0.tar.xz : ce743cd80c0e2d525a784e29c9b487f73480119b0567f9ce8ef1f44cca527587
license    : GPL-3.0-or-later
component  : network.web.browser
summary    : Falkon (formerly QupZilla) is a new and very fast QtWebEngine browser
description: |
    Falkon (formerly QupZilla) is a new and very fast QtWebEngine browser
replaces   :
    - qupzilla
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5WebEngine)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(xcb-atom)
    - extra-cmake-modules
    - kcrash-devel
    - ki18n-devel
    - kio-devel
    - kwallet-devel
    - purpose-devel
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
    install -Dm00644 linux/completion/_falkon $installdir/usr/share/zsh/site-functions/_falkon
